### ISSUE TITLE
Datapusher Error - Authorization 

### ISSUE THREAD

**Issue by 3vivekb** [keitaroinc/docker-ckan-datapusher#1]
Got farther with your docker datapusher code than anything else i've tried.  It becomes responsive but ckan gives this error.  Any thoughts?

In Docker-Compose:
ckan          | 2017-02-23 21:58:40,052 INFO  [ckan.lib.base]  /dataset/test-4/resource_data/1aec102a-035e-4f7b-856b-e9eaf49510d8 render time 0.144 seconds
ckan          | 2017-02-23 21:58:40,451 INFO  [ckan.lib.base]  /dataset/49de5ea7-29c2-431f-ab27-eaaf74d9469b/resource/1aec102a-035e-4f7b-856b-e9eaf49510d8/download/techcrunchcontinentalusa-2.csv render time 0.461 seconds
ckan          | 2017-02-23 21:58:40,520 INFO  [ckan.lib.base]  /api/i18n/en render time 0.002 seconds
ckan          | 2017-02-23 21:58:40,645 INFO  [ckan.lib.base]  /api/3/action/datapusher_hook render time 0.015 seconds
ckan_datapusher | --------------------------------------------------------------------------------
ckan_datapusher | ERROR in scheduler [/usr/lib/python2.7/site-packages/apscheduler/scheduler.py:520]:
ckan_datapusher | Job "push_to_datastore (trigger: RunTriggerNow, run = True, next run at: None)" raised an exception
ckan_datapusher | --------------------------------------------------------------------------------
ckan_datapusher | Traceback (most recent call last):
ckan_datapusher |   File "/usr/lib/python2.7/site-packages/apscheduler/scheduler.py", line 512, in _run_job
ckan_datapusher |     retval = job.func(*job.args, **job.kwargs)
ckan_datapusher |   File "build/bdist.linux-x86_64/egg/datapusher/jobs.py", line 321, in push_to_datastore
ckan_datapusher |     request_url=resource.get('url'), response=e.read())
ckan_datapusher | HTTPError

On the site:
Error: DataPusher received a bad HTTP response when trying to download the data file 
HTTP status code: 400 
Response: <?xml version="1.0" encoding="UTF-8"?> <Error><Code>InvalidArgument</Code><Message>Authorization header is invalid -- one and only one ' ' (space) required</Message><ArgumentName>Authorization</Argume... 
Requested URL: http://data2.vta.org/dataset/49de5ea7-29c2-431f-ab27-eaaf74d9469b/resource/1aec102a-035e-4f7b-856b-e9eaf49510d8/download/techcrunchcontinentalusa-2.csv

**Comment by mbocevski** [comment]
I wasn't able to access the URL that you've specified. The error you're getting looks to be a setup issue. Can you access the resource URL from the datapusher container?

**Comment by 3vivekb** [comment]
I sorta figured out the error and a hack to get around it.  I detailed it in this issue https://github.com/ckan/datapusher/issues/116.
Overall your docker container works great!  It's super hard to modify and debug though but it's "done" so no big deal.  I modified it a little to point to my repo where I put my hack.

**Comment by mbocevski** [comment]
@3vivekb Thanks. Will check the issue you reported on datapusher and figure what might be causing the issue. This container is built to be very slim that's why the Dockerfile looks like that. Any suggestions welcomed.

**Comment by Rjones8901** [comment]
Any movement on this issue? I am seeing this too. We are not using docker, but are seeing "Error: DataPusher received a bad HTTP response when trying to download the data file". It appears to be an issue in the way the authorization is being constructed.

**Comment by 3vivekb** [comment]
Hey @Rjones8901 I did a hacky workaround.  Check out this file - https://github.com/vta/Open-Data-Portal/blob/master/datapusher/Dockerfile
I forked the repo and disabled private auth and it works for public datasets.
